# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0005_auto_20161210_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='client_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='server_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
