# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import surfer.models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0007_auto_20161210_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=surfer.models.file_path)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfer.Channel')),
            ],
        ),
    ]
