# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0008_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
