# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0012_channel_is_initialized'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(3, 'Transitioner'), (1, 'Controller'), (2, 'Picker'), (0, 'Communicator')], max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfer.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ControllerPartOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('documentation', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('fixed', models.BooleanField(default=False)),
                ('controller_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfer.ControllerPart')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
