# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0014_auto_20170117_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_played', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfer.Channel')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surfer.File')),
            ],
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(3, 'Transitioner'), (1, 'Controller'), (2, 'Picker'), (0, 'Communicator')]),
        ),
    ]
