# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0015_auto_20170118_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControllerPartOptions',
            new_name='ControllerPartOption',
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(0, 'Communicator'), (1, 'Controller'), (2, 'Picker'), (3, 'Transitioner')]),
        ),
    ]
