# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0017_auto_20170120_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerpart',
            name='long_doc',
            field=models.TextField(default='no desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controllerpart',
            name='short_doc',
            field=models.CharField(default='no desc', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(3, 'Transitioner'), (0, 'Communicator'), (1, 'Controller'), (2, 'Picker')]),
        ),
    ]
