# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0018_auto_20170121_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(0, 'Communicator'), (1, 'Controller'), (3, 'Transitioner'), (2, 'Picker')]),
        ),
    ]
