# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0012_auto_20170120_1228'),
        ('surfer', '0019_auto_20170122_1950'),
    ]

    operations = [
    ]
