# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0020_merge_20170122_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='docker_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='output_dir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='socket',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(1, 'Controller'), (2, 'Picker'), (0, 'Communicator'), (3, 'Transitioner')]),
        ),
    ]
