# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0021_auto_20170123_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='input_dir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(3, 'Transitioner'), (1, 'Controller'), (0, 'Communicator'), (2, 'Picker')]),
        ),
    ]
