# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0023_file_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='epoch',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(3, 'Transitioner'), (1, 'Controller'), (2, 'Picker'), (0, 'Communicator')]),
        ),
    ]
