# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0024_auto_20170123_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(0, 'Communicator'), (1, 'Controller'), (3, 'Transitioner'), (2, 'Picker')]),
        ),
    ]
