# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0025_auto_20170123_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_starting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(0, 'Communicator'), (3, 'Transitioner'), (2, 'Picker'), (1, 'Controller')]),
        ),
    ]
