# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0026_auto_20170123_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerpartoption',
            name='value',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(3, 'Transitioner'), (2, 'Picker'), (0, 'Communicator'), (1, 'Controller')]),
        ),
    ]
