# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0027_auto_20170123_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerpart',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(2, 'Picker'), (0, 'Communicator'), (1, 'Controller'), (3, 'Transitioner')]),
        ),
    ]
