# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0028_auto_20170123_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='settings_committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(1, 'Controller'), (2, 'Picker'), (0, 'Communicator'), (3, 'Transitioner')]),
        ),
    ]
