# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0029_auto_20170124_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='has_started',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='is_initialized',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='settings_committed',
        ),
        migrations.AddField(
            model_name='channel',
            name='state',
            field=models.IntegerField(choices=[(1, 'Initialized'), (3, 'Starting'), (2, 'Committed'), (4, 'Started'), (0, 'Initializing')], default=0),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(1, 'Controller'), (0, 'Communicator'), (3, 'Transitioner'), (2, 'Picker')]),
        ),
    ]
