# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0030_auto_20170129_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='has_started',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_starting',
        ),
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=models.IntegerField(choices=[(2, 'Committed'), (0, 'Initializing'), (3, 'Starting'), (4, 'Started'), (1, 'Initialized')], default=0),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(1, 'Controller'), (2, 'Picker'), (3, 'Transitioner'), (0, 'Communicator')]),
        ),
    ]
