# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0034_auto_20170130_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playedfile',
            name='channel',
        ),
        migrations.AlterField(
            model_name='channel',
            name='color',
            field=models.CharField(default='#1abc9c', max_length=7),
        ),
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=models.IntegerField(choices=[(4, 'Started'), (0, 'Initializing'), (1, 'Initialized'), (3, 'Starting'), (2, 'Committed')], default=0),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(0, 'Communicator'), (3, 'Transitioner'), (2, 'Picker'), (1, 'Controller')]),
        ),
    ]
