# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0036_auto_20170130_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=models.IntegerField(choices=[(4, 'Started'), (1, 'Initialized'), (2, 'Committed'), (0, 'Initializing'), (3, 'Starting')], default=0),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(1, 'Controller'), (2, 'Picker'), (0, 'Communicator'), (3, 'Transitioner')]),
        ),
    ]
