# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfer', '0037_auto_20170201_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=models.IntegerField(choices=[(3, 'Starting'), (1, 'Initialized'), (0, 'Initializing'), (4, 'Started'), (2, 'Committed')], default=0),
        ),
        migrations.AlterField(
            model_name='controllerpart',
            name='category',
            field=models.IntegerField(choices=[(2, 'Picker'), (0, 'Communicator'), (1, 'Controller'), (3, 'Transitioner')]),
        ),
    ]
